import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9f9f9',
    padding: 20,
  },
  textOdakent: {
    top: -30,
    marginBottom: -10,
    width: '100%',
    alignItems: 'center',
    paddingHorizontal: 0,
  },
  odakentText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    letterSpacing: 2,
  },
  input: {
    backgroundColor: 'white',
    height: 45,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 10,
    marginVertical: 10,
    fontSize: 16,
  },
  button: {
    flexDirection: 'row',
    justifyContent: 'center',
    backgroundColor: '#197ce6',
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: 'center',
    marginVertical: 15,
  },
  buttonModal: {
    marginTop: 10,
    backgroundColor: '#197ce6',
    paddingVertical: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  buttonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: 'bold',
  },
  userButton: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
    backgroundColor: '#0eab61',
    paddingVertical: 12,
    borderRadius: 5,
    alignItems: 'center',
    marginVertical: 10,
  },
  modalContainer: {
    maxHeight: 700,
    margin: 10,
    backgroundColor: '#d3e0ed',
    padding: 18,
    borderRadius: 10,
    position: 'relative',
  },
  modalContainerUser: {
    margin: 10,
    backgroundColor: '#d3e0ed',
    padding: 20,
    borderRadius: 10,
    position: 'relative',
  },
  closeButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 10,
  },
  modalText: {
    fontSize: 18,
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 20,
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  modalButton: {
    backgroundColor: '#197ce6',
    paddingVertical: 10,
    borderRadius: 5,
    width: '45%',
    alignItems: 'center',
  },
  userModalButton: {
    backgroundColor: '#0eab61',
    paddingVertical: 10,
    borderRadius: 5,
    width: '45%',
    alignItems: 'center',
  },
  modalButtonText: {
    color: 'white',
    fontSize: 16,
  },
  dropdown: {
    backgroundColor: 'white',
    height: 50,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 5,
    marginVertical: 10,
    paddingHorizontal: 10,
    fontSize: 16,
  },
  icon: {
    marginRight: 10,
  },
  iconInButton: {
    marginRight: 10,
  },
  kohanaInput: {
    marginTop: 10,
    marginBottom: 16,
    backgroundColor: 'white',
    borderRadius: 5,
  },
  placeholderStyle: {
    color: '#999',
    fontSize: 16,
  },
  selectedTextStyle: {
    color: '#999',
    fontSize: 16,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
    backgroundColor: 'white',
  },
  itemTextStyle: {
    color: '#999',
  },
  itemContainer: {
    width: '100%',
    height: 'auto',
    padding: 10,
    marginTop: 2,
    marginBottom: 5,
    backgroundColor: '#fff',
    flexDirection: 'column',
  },
  contentContainer: {
    paddingBottom: 15,
    paddingTop: 10,
    height: 'auto',
  },
  titleText: {
    width: '80%',
    fontWeight: 'bold',
    marginBottom: 5,
  },
  searchContainer: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.5,
    backgroundColor: 'white',
    borderColor: 'black',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 36,
    marginBottom: 10,
  },
  searchInput: {
    flex: 1,
    padding: 8,
  },
});

export default styles;
