import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: '#f3f4f4',
    padding: 5,
  },
  scrollViewContainer: {
    flex: 1,
  },
  titleText: {
    padding: 5,
    fontSize: 20,
    fontWeight: 'bold',
    marginLeft: 15,
    color: '#333',
    marginBottom: 15,
    lineHeight: 22,
  },
  itemText: {
    padding: 5,
    marginTop: 15,
    marginLeft: 15,
    fontSize: 16,
    color: '#555',
    marginBottom: 20,
    lineHeight: 22,
  },
  itemImage: {
    maxWidth: 150,
    height: 150,
    resizeMode: 'cover',
    borderRadius: 10,
    marginLeft: 15,
    marginTop: 15,
  },
  chatTitle: {
    marginTop: 20,
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  messageText: {
    fontSize: 15,
    color: 'black',
    lineHeight: 22,
    fontWeight: '400',
    paddingVertical: 2,
    paddingHorizontal: 6,
  },

  messageRow: {
    width: '100%',
    marginVertical: 4,
    alignItems: 'flex-start',
  },
  ownMessageRow: {
    alignItems: 'flex-end',
  },
  messageBox: {
    maxWidth: '100%',
    padding: 4,
    borderRadius: 12,
    borderBottomRightRadius: 0,
  },
  ownMessage: {
    backgroundColor: '#54ad36',
  },
  otherMessage: {
    backgroundColor: '#3998e6',
  },
  messageInfoContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 2,
    alignSelf: 'flex-end',
    maxWidth: '80%',
  },
  messageInfo: {
    fontSize: 12,
    fontWeight: '600',
    color: '#eed',
    textAlign: 'right',
    letterSpacing: 0.5,
  },
  inputContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#FFF',
    borderTopWidth: 1,
    borderColor: '#EEE',
  },

  sendButton: {
    backgroundColor: '#4CAF50',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 2,
  },

  sendButtonText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 16,
  },

  cameraIcon: {
    color: '#555',
    marginHorizontal: 10,
    padding: 5,
    backgroundColor: '#F0F0F0',
    borderRadius: 5,
  },

  input: {
    flex: 1,
    height: 40,
    paddingHorizontal: 10,
    backgroundColor: '#EFEFEF',
    borderRadius: 8,
    color: '#333',
    fontSize: 15,
    marginRight: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 1},
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },

  chatContainer: {
    overflow: 'scroll',
    flex: 1,
    borderRadius: 10,
    width: '100%',
    height: 550,
    marginBottom: 63,
  },
  chatImage: {
    borderRadius: 10,
    width: 160,
    height: 160,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
  },
  modalImage: {
    width: '90%',
    height: '80%',
    resizeMode: 'contain',
    borderRadius: 10,
  },
  closeButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    padding: 4,
    zIndex: 1,
  },
  closeIcon: {
    color: 'white',
    fontSize: 30,
  },
  buttonStatuContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  buttonStatu: {
    borderRadius: 10,
    marginRight: 5,
    paddingVertical: 6,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  buttonStatuText: {
    fontSize: 12,
    color: 'black',
    fontWeight: 'bold',
  },
  deleteButton: {
    marginRight: 10,
    marginLeft: 10,
  },
  cancelButton: {
    backgroundColor: '#dcdcdc',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContainerDelete: {
    width: '75%',
    height: '25%',
    padding: 20,
    backgroundColor: '#ffffff',
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 5,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ff4c4c',
  },
  modalDescription: {
    fontSize: 14,
    color: '#333',
    marginVertical: 10,
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 20,
    marginTop: 20,
  },
  button: {
    width: 120,
    paddingVertical: 10,
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonText: {
    color: 'black',
    fontWeight: 'bold',
  },
});

export default styles;
